### PR TITLE
Fix page title

### PR DESCRIPTION
**Pull request by infinisil**
It's not NixOS Infra Status

### CODE REVIEW

**Review by samueldr — APPROVED** [review]

**Comment by infinisil** [comment]
Hmm actually there are Grafana and Prometheus links above. Maybe it should be "NixOS Status" instead, matching the text at the top left.

**Comment by samueldr** [comment]
Or `NixOS Status — Channels Status`.

**Comment by infinisil** [comment]
Updated to just use "NixOS Status" to match

**Comment by infinisil** [comment]
Ping @garbas, can you merge this?

**Review by garbas — APPROVED** [review]

**Pull request merged**
